Create Banner Component
web-seven/website pull request #42
Opened 2023-12-07 10:07 UTC by BurlacuLucian

2023-12-07 10:29 UTC, BurlacuLucian commented
it's all right
I told you that Storybook does not always receive the styles
![Screenshot_20231207_122533](https://github.com/web-seven/website/assets/122973516/00b3311a-2977-498e-9abe-735480789fef)

2023-12-08 07:40 UTC, web7evgheni requested changes

2023-12-08 07:40 UTC, web7evgheni commented on src/components/BannerComponent.tsx
> +export const BannerComponent = (props) => {
@BurlacuLucian Please rename it to simple "Banner", you never used Component suffix, let'd keep this practice.

2023-12-11 09:27 UTC, web7evgheni approved these changes

2023-12-11 09:27 UTC, merged