Create About Us Page
web-seven/website pull request #60
Opened 2023-12-12 11:58 UTC by BurlacuLucian

2023-12-12 11:59 UTC, web7evgheni commented
@BurlacuLucian Pages shall be in MD format, but please give back this issue to @Enotmd

2023-12-12 12:00 UTC, web7evgheni requested changes
@Enotmd please take care of this PR and create MD version of this page.

2023-12-12 13:39 UTC, Enotmd approved these changes

2023-12-13 09:14 UTC, Enotmd approved these changes

2023-12-13 19:58 UTC, web7evgheni requested changes
@Enotmd Please add content

2023-12-14 12:15 UTC, closed without merging